version: '3.4'

services:
  database:
    build: ./db
  server:
    build:
      context: 'server/'
      dockerfile: '/Users/ashishgyawali/Documents/docker-compose/server/Dockerfile'
    ports:
      - '8090:8090'
    depends_on:
      - database
    volumes: -./server:/app
  client:
    build:
      context: 'client/'
      dockerfile: '/Users/ashishgyawali/Documents/docker-compose/client/Dockerfile'
    ports:
      - '3003:3003'
    volumes:
      - ./client:/app
